const CURRENCY='CAD';
const categories={
  money:{name:'Money',icon:'💰',desc:'Savings, borrowing and everyday money math'},
  retirement:{name:'Retirement',icon:'🧓',desc:'Countdowns and long-term planning estimates'},
  time:{name:'Time & Dates',icon:'📅',desc:'Ages, intervals and countdowns'},
  everyday:{name:'Everyday Life',icon:'🏠',desc:'Shopping, ownership and bill-splitting'},
  travel:{name:'Travel',icon:'✈️',desc:'Trip budgets and driving costs'},
  health:{name:'Health & Fitness',icon:'❤️',desc:'General fitness and pace estimates'}
};
const calculators=[
 {id:'compound-growth',title:'Compound Growth',icon:'📈',category:'money',description:'See how savings can grow with contributions, returns and inflation.',keywords:'investment interest compounding savings future value popular'},
 {id:'savings-goal',title:'Savings Goal',icon:'🎯',category:'money',description:'Find the monthly savings needed for a target—or how long it may take.',keywords:'investment goal monthly contribution save target'},
 {id:'inflation',title:'Inflation',icon:'🪙',category:'money',description:'Compare future purchasing power with today’s dollars.',keywords:'purchasing power real value future value CPI'},
 {id:'mortgage',title:'Mortgage',icon:'🏡',category:'money',description:'Estimate Canadian mortgage payments, interest and prepayment savings.',keywords:'home house loan amortization payment Canadian popular'},
 {id:'car-loan',title:'Loan / Car Payment',icon:'🚗',category:'money',description:'Estimate financed cost, payment and interest, or compare two offers.',keywords:'auto vehicle financing car loan payment'},
 {id:'percentage',title:'Percentage Calculator',icon:'％',category:'money',description:'Fast percentage, discount, change and difference calculations.',keywords:'percent discount increase decrease popular'},
 {id:'retirement-countdown',title:'Retirement Countdown',icon:'🌅',category:'retirement',description:'Count the years, months and days until your planned retirement.',keywords:'retire age working days savings'},
 {id:'money-longevity',title:'How Long Will My Money Last?',icon:'⏳',category:'retirement',description:'Model portfolio withdrawals, growth and inflation over time.',keywords:'investment portfolio withdrawal retirement money longevity'},
 {id:'age',title:'Age',icon:'🎂',category:'time',description:'Calculate exact age, total days and days until the next birthday.',keywords:'birthday date years months days popular'},
 {id:'date-difference',title:'Date Difference',icon:'↔️',category:'time',description:'Measure the interval between two dates in several useful ways.',keywords:'days between dates weekdays weekends birthday popular'},
 {id:'countdown',title:'Countdown',icon:'⏰',category:'time',description:'Create live countdowns for vacations, birthdays and other events.',keywords:'timer vacation cruise appointment birthday event'},
 {id:'cost-per-use',title:'Cost Per Use',icon:'🔁',category:'everyday',description:'Estimate what an item really costs each time you use it.',keywords:'ownership shopping value purchase cost per month'},
 {id:'unit-price',title:'Unit Price Comparison',icon:'⚖️',category:'everyday',description:'Compare package sizes and find the best price per unit.',keywords:'grocery shopping compare price grams litres value popular'},
 {id:'tip-split',title:'Tip & Bill Split',icon:'🧾',category:'everyday',description:'Calculate tip, total bill and per-person share in seconds.',keywords:'restaurant gratuity split bill'},
 {id:'travel-budget',title:'Travel Budget',icon:'🧳',category:'travel',description:'Estimate total trip cost, per-person cost and daily spending.',keywords:'vacation flight hotel accommodation trip currency'},
 {id:'currency-converter',title:'Currency Converter',icon:'💱',category:'travel',description:'Convert Canadian dollars and seven common travel currencies using daily reference rates.',keywords:'currency exchange rate forex Canadian CAD USD US dollar HKD Hong Kong JPY yen Japan MXN peso Mexico EUR euro TWD Taiwan KRW Korean won travel money'},
 {id:'fuel-cost',title:'Fuel Cost',icon:'⛽',category:'travel',description:'Calculate fuel needed and trip cost across metric or imperial units.',keywords:'car driving gas petrol mileage MPG'},
 {id:'bmi',title:'BMI',icon:'📏',category:'health',description:'Calculate body mass index using metric or imperial measurements.',keywords:'body mass index weight height health'},
 {id:'pace',title:'Walking / Running Pace',icon:'🏃',category:'health',description:'Convert distance, time and pace for walks, runs and races.',keywords:'running walking 5k 10k marathon speed pace'}
];
const popular=['compound-growth','mortgage','age','date-difference','unit-price','percentage'];
const financialIds=new Set(['compound-growth','savings-goal','inflation','mortgage','car-loan','percentage','retirement-countdown','money-longevity','cost-per-use','unit-price','tip-split','travel-budget','fuel-cost']);
const healthIds=new Set(['bmi']);
const state={query:'',category:'all'};
const fmtMoney=(v,d=0)=>Number.isFinite(v)?new Intl.NumberFormat('en-CA',{style:'currency',currency:CURRENCY,maximumFractionDigits:d,minimumFractionDigits:d}).format(v):'—';
const fmtNum=(v,d=1)=>Number.isFinite(v)?new Intl.NumberFormat('en-CA',{maximumFractionDigits:d}).format(v):'—';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const getNum=(id)=>{const el=document.getElementById(id); if(!el)return NaN; const v=parseFloat(String(el.value).replace(/,/g,'')); return Number.isFinite(v)?v:NaN};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const plural=(n,w)=>`${n} ${w}${n===1?'':'s'}`;
function getFavs(){try{return JSON.parse(localStorage.getItem('lifeCalcFavs')||'[]')}catch{return[]}}
function setFavs(v){localStorage.setItem('lifeCalcFavs',JSON.stringify(v))}
function toggleFav(id){const s=new Set(getFavs());s.has(id)?s.delete(id):s.add(id);setFavs([...s]);updateFavButtons(id);}
function updateFavButtons(id){const yes=getFavs().includes(id);document.querySelectorAll(`[data-fav="${id}"]`).forEach(b=>{b.textContent=yes?'★ Favorited':'☆ Favorite';b.setAttribute('aria-pressed',String(yes))});document.querySelectorAll(`[data-favmini="${id}"]`).forEach(b=>{b.textContent=yes?'★':'☆';b.setAttribute('aria-label',yes?'Remove from favorites':'Add to favorites')})}
function markRecent(id){let r=[];try{r=JSON.parse(localStorage.getItem('lifeCalcRecent')||'[]')}catch{};r=[id,...r.filter(x=>x!==id)].slice(0,5);localStorage.setItem('lifeCalcRecent',JSON.stringify(r))}
function getRecent(){try{return JSON.parse(localStorage.getItem('lifeCalcRecent')||'[]')}catch{return[]}}
function basePath(){const p=location.pathname;const i=p.indexOf('/life-calculators');return i>=0?p.slice(0,i)+'/life-calculators':'/life-calculators'}
function calcHref(id){return `${basePath()}/${id}/`}
function currentId(){const m=location.pathname.match(/\/life-calculators\/([^/]+)/);if(m&&calculators.some(c=>c.id===m[1]))return m[1];const q=new URLSearchParams(location.search).get('calc');if(q&&calculators.some(c=>c.id===q))return q;return null}
function navigate(id){if(location.protocol==='file:'){location.hash=id?`#${id}`:'#home';return} history.pushState({},'',id?calcHref(id):basePath()+'/');render()}
function card(c){const fav=getFavs().includes(c.id);return `<article class="calc-card" data-open="${c.id}" tabindex="0" role="link" aria-label="Open ${esc(c.title)}"><div class="card-top"><div class="card-icon">${c.icon}</div><div><div class="card-title">${esc(c.title)}</div><div class="card-desc">${esc(c.description)}</div></div></div><div class="card-footer"><span class="tag">${categories[c.category].name}</span><button class="fav-mini" data-favmini="${c.id}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'★':'☆'}</button></div></article>`}
function dashboard(){document.title='Life Calculators';document.querySelector('meta[name="description"]').content='Simple calculators for money, time, travel, health, and everyday life.'; const favs=getFavs().map(id=>calculators.find(c=>c.id===id)).filter(Boolean);const recent=getRecent().map(id=>calculators.find(c=>c.id===id)).filter(Boolean);const filtered=calculators.filter(c=>{const q=state.query.trim().toLowerCase();const cat=state.category==='all'||c.category===state.category;const match=!q||(`${c.title} ${c.description} ${c.keywords} ${categories[c.category].name}`).toLowerCase().includes(q);return cat&&match});return `
<section class="hero" id="home"><h1>Life Calculators</h1><p>Simple calculators for money, time, travel, health, and everyday life.</p><div class="hero-search"><span class="search-icon">⌕</span><input id="heroSearch" type="search" value="${esc(state.query)}" placeholder="What do you want to calculate?" aria-label="Search calculators"></div></section>
${!state.query&&state.category==='all'&&favs.length?`<section class="section" id="favorites"><div class="section-head"><h2>Favorites</h2><span class="section-note">Saved only on this device</span></div><div class="grid">${favs.map(card).join('')}</div></section>`:''}
${!state.query&&state.category==='all'?`<section class="section"><div class="section-head"><h2>Popular Calculators</h2><span class="section-note">Quick everyday tools</span></div><div class="grid">${popular.map(id=>card(calculators.find(c=>c.id===id))).join('')}</div></section>`:''}
<section class="section" id="categories"><div class="section-head"><h2>Categories</h2><span class="section-note">Find a calculator in 1–2 clicks</span></div><div class="grid">${Object.entries(categories).map(([id,c])=>`<button class="category-card" data-cat="${id}"><div class="card-icon">${c.icon}</div><strong>${c.name}</strong><span>${c.desc}</span></button>`).join('')}</div></section>
<section class="section" id="all"><div class="section-head"><h2>${state.query?'Search Results':state.category==='all'?'All Calculators':categories[state.category].name}</h2><span class="section-note">${filtered.length} calculator${filtered.length===1?'':'s'}</span></div><div class="filter-row"><button class="chip ${state.category==='all'?'active':''}" data-cat="all">All</button>${Object.entries(categories).map(([id,c])=>`<button class="chip ${state.category===id?'active':''}" data-cat="${id}">${c.icon} ${c.name}</button>`).join('')}</div>${filtered.length?`<div class="grid" style="margin-top:14px">${filtered.map(card).join('')}</div>`:`<div class="empty" style="margin-top:14px">No calculators match that search yet.</div>`}</section>
${!state.query&&state.category==='all'&&recent.length?`<section class="section"><div class="section-head"><h2>Recently Used</h2><span class="section-note">Calculator names only</span></div><div class="grid">${recent.map(card).join('')}</div></section>`:''}
<section class="section"><div class="privacy-card"><strong>Privacy by design.</strong> Life Calculators performs calculations in your browser. Calculator information is generally not uploaded or stored on a server. Favorites, recently used calculator names, saved countdowns and basic preferences may be stored locally on your device.</div></section>`}
function layout(c,content){markRecent(c.id);const pageName=/(Calculator|Converter)$/i.test(c.title)?c.title:`${c.title} Calculator`;document.title=`${pageName} | Life Calculators`;document.querySelector('meta[name="description"]').content=c.description;const fav=getFavs().includes(c.id);return `<div class="calc-wrap"><a class="back" href="${basePath()}/" data-go-home>← Back to Calculators</a><header class="calc-header"><div class="card-icon">${c.icon}</div><div><h1>${esc(c.title)}</h1><p>${esc(c.description)}</p><div class="calc-tools"><button class="ghost-btn" data-fav="${c.id}" aria-pressed="${fav}">${fav?'★ Favorited':'☆ Favorite'}</button><button class="ghost-btn" data-copy>⧉ Copy Result</button><button class="ghost-btn" data-share>↗ Share</button></div></div></header>${content}<div class="disclaimer">${healthIds.has(c.id)?'This tool provides general informational estimates and is not a substitute for professional medical advice, diagnosis, or treatment.':financialIds.has(c.id)?'These calculators are provided for general educational and planning purposes only. Results are estimates based on the assumptions entered and should not be considered financial, tax, investment, or legal advice.':'Results are estimates based on the information entered.'}</div></div>`}
function field(id,label,value,opt={}){const {prefix='',suffix='',type='number',step='any',min='0',max='',hint='',placeholder=''}=opt;return `<div class="field"><label for="${id}">${label}</label><div class="input-wrap">${prefix?`<span class="prefix">${prefix}</span>`:''}<input id="${id}" type="${type}" ${type==='number'?`inputmode="decimal" step="${step}" ${min!==null?`min="${min}"`:''} ${max!==''?`max="${max}"`:''}`:''} value="${esc(value)}" placeholder="${esc(placeholder)}" class="${prefix?'has-prefix ':''}${suffix?'has-suffix':''}">${suffix?`<span class="suffix">${suffix}</span>`:''}</div>${hint?`<div class="hint">${hint}</div>`:''}</div>`}
function selectField(id,label,opts,value){return `<div class="field"><label for="${id}">${label}</label><select id="${id}">${opts.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select></div>`}
function resultBox(label,value,sub='',metrics=[]){return `<section class="panel" id="results" aria-live="polite"><div class="result-hero"><div class="result-label">${label}</div><div class="result-value">${value}</div>${sub?`<div class="result-sub">${sub}</div>`:''}</div>${metrics.length?`<div class="result-grid">${metrics.map(m=>`<div class="metric"><span>${m[0]}</span><b>${m[1]}</b></div>`).join('')}</div>`:''}</section>`}
function lineChart(values,labels){if(!values.length)return'';const W=760,H=250,p=36;const max=Math.max(...values,1),min=Math.min(...values,0),range=max-min||1;const pts=values.map((v,i)=>{const x=p+(W-2*p)*(i/(values.length-1||1));const y=H-p-(H-2*p)*((v-min)/range);return[x,y]});const poly=pts.map(p=>p.join(',')).join(' ');const area=`${p},${H-p} ${poly} ${W-p},${H-p}`;let grid='';for(let i=0;i<4;i++){const y=p+(H-2*p)*i/3;const val=max-(range*i/3);grid+=`<line class="gridline" x1="${p}" x2="${W-p}" y1="${y}" y2="${y}"/><text x="4" y="${y+4}">${fmtNum(val,0)}</text>`}const end=labels[labels.length-1]||'';return `<div class="chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="Line chart">${grid}<polygon class="area" points="${area}"/><polyline class="line" points="${poly}"/><text x="${p}" y="${H-8}">${esc(labels[0]||'')}</text><text x="${W-p}" y="${H-8}" text-anchor="end">${esc(end)}</text></svg></div>`}
function setResultText(t){window.__lastResultText=t}
function attachCommon(c){document.querySelectorAll(`[data-fav="${c.id}"]`).forEach(b=>b.onclick=()=>toggleFav(c.id));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const t=window.__lastResultText||`${c.title} calculator result`;try{await navigator.clipboard.writeText(t);b.textContent='✓ Copied';setTimeout(()=>b.textContent='⧉ Copy Result',1300)}catch{alert(t)}});document.querySelectorAll('[data-share]').forEach(b=>b.onclick=async()=>{const t=window.__lastResultText||`${c.title} calculator`;if(navigator.share)try{await navigator.share({title:`${c.title} | Life Calculators`,text:t,url:location.href})}catch{}else try{await navigator.clipboard.writeText(t);b.textContent='✓ Copied link'}catch{}})}
function validNums(arr){return arr.every(Number.isFinite)}
function error(msg){return `<div class="error">${esc(msg)}</div>`}
